### ISSUE TITLE
v0.4.0 roadmap

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#108]
v0.2.0 roadmap:  #49

v0.3.0 saw support for Tricolor Turf War added (65ae361) and didn't need a roadmap 😊

We don't know exactly what updates SplatNet 3 will get for new Splatoon 3 Ver.3.0.0 content (so many [3](https://i.imgur.com/szCBbpm.jpg)s…!) but here's what I'm hoping for.

## v0.4.0 roadmap

General :
- [x] New `-o` export format (v0.3.2 / 38e93c2)
- [x] Find SplatNet IDs for new [battle](https://github.com/frozenpandaman/s3s/wiki/%7C-stat.ink-&-splatnet-keys#stages) & [Big Run](https://github.com/frozenpandaman/s3s/wiki/%7C-stat.ink-&-splatnet-keys#salmon-run) stages & have @fetus-hina add stat.ink support
- [x] Find SplatNet ID for new [SR King Salmonid](https://github.com/frozenpandaman/s3s/wiki/%7C-stat.ink-&-splatnet-keys#bosses--kings) (Horrorboros)
- [x] #115 (v0.3.4 / ff2c95b)
- [x] Support new [SR gear](https://github.com/frozenpandaman/s3s/wiki/%7C-stat.ink-&-splatnet-keys#uniforms), #112 (v0.3.3 / 309640e)
- [x] NSO 2.5.0 heders (v0.3.3 / 8b6df18)

Closing out (new & old) issues/PRs:
- [x] #113 (v0.3.3 / 5cae354, d15c336)

~~Tableturf Battle:~~
  * Unsupported in SplatNet 3 for now

Eggstra Work:
- [x] Full support (v0.4.0 / d46ece0)

**Comment by frozenpandaman** [comment]
(Apparently I don't know what version we're on or can't count or something. Nice.)

**Comment by frozenpandaman** [comment]
v0.4.0 has been released as of 4/15/23!

Remaining open issues for a future (minor) update:
- [ ] #116  /   
#111
- [ ] QOL: #64 
- [ ] QOL: #17
