### ISSUE TITLE
v0.5.0 roadmap

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#128]
v0.4.0 roadmap:  #108

## v0.5.0 roadmap

- Support for Challenges
  - [x] Support for Challenge mode lobby type (`vsMode.mode` = `LEAGUE`; stat.ink key = `event`)
  - [x] Specific challenge info (`leagueMatch.leagueMatchEvent.id`; stat.ink key = `event`)
  - [x] Team power (`leagueMatch.myLeaguePower`; stat.ink key = `event_power`)
- Integrate outstanding PRs / fix issues
  - [x] #126
    - Which also takes care of #116 & #111

**Comment by frozenpandaman** [comment]
This is now out. I was a little too fast in incrementing the version number, and in getting the update out without everything quite fully checked + complete. Per https://stat.ink/entire/users, 13 users had already upgraded, though, so I had to bump the version number again as part of the change to ensure stats will send correctly for the upcoming ranked-mode Challenge this weekend (and so the auto-update function will prompt these users to update…) 

v0.5.1 and (hopefully) full support for challenges is live as of e52c599.
