### ISSUE TITLE
v0.6.0 roadmap

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#155]
v0.5.0 roadmap: https://github.com/frozenpandaman/s3s/issues/128

- [x] Ver.6.0.0 support: https://github.com/frozenpandaman/s3s/pull/158 (https://github.com/frozenpandaman/s3s/commit/fec715bea13a2e69ab0acfebe6fc95b8b94be0c0), https://github.com/frozenpandaman/s3s/pull/156
- [x] Bump NSO to 2.8.1 https://github.com/frozenpandaman/s3s/commit/da6829b7826a46c33530f48d5043a98484c56203 
- [x] https://github.com/frozenpandaman/s3s/pull/145 48e3d5a
- [x] https://github.com/frozenpandaman/s3s/pull/159 541378a 5e7d854 a1ee8aa
- [x] Code cleanup [059b3ea](https://github.com/frozenpandaman/s3s/commit/059b3ea364785cdd4434f12dbb92bc0d822a347f) 

Maybe:
- [x] ~~https://github.com/frozenpandaman/s3s/issues/144~~ – Addressed, bumped to v0.6.1+
- [x] ~~GitHub Actions for building program executables?~~ – v0.6.1+ (lol)

**Comment by niyari** [comment]
https://github.com/frozenpandaman/s3s/blob/18ac2ebdc7fe3f9d55a716a64fce6500707e0952/iksm.py#L9
-> `True`

**Comment by frozenpandaman** [comment]
@niyari Oh, great! That didn't work for me during my testing, so I thought there was an issue, but I was doing it at 3 a.m. so I probably was doing it wrong 😆

Still, the Salmon Run job details query needs to be changed to the new value, and possibly a couple other fields supported (depending on what stat.ink does) so I'll leave this open for now...

**Comment by frozenpandaman** [comment]
#156 and #158 merged.

I'll wait on bumping the version number to `v0.6.0` until I can look at #144 & #145 in a couple days.

**Comment by qjzcj2008** [comment]
The f API is always associated with the NSO version number. Mismatched NSO version sent to The f API could result in errors, just like this time.

So I think get NSO version number from Apple App Store may not the best choice, and the major f APIs provide a `/config` endpoint to provide the NSO version they're running. Maybe use NSO version from f APIs will be better.

I make a PR about this.#159 It should be compatible with existing version s3s, and when get NSO version from The f APIs failed it will fallback to APP Store.

**Comment by frozenpandaman** [comment]
v0.6.0 is now out: 059b3ea

Sorry for the delay; all users should now be prompted to auto-update which will fix the new specials in SR issue (without having to manually do a `git pull`) along with other improvements.

**Comment by frozenpandaman** [comment]
Re-opening, #159 introduces a breaking error.

**Comment by frozenpandaman** [comment]
Fixed in c110e2e, v0.6.0 re-released :^)
