### ISSUE TITLE
v0.1.0 roadmap

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#20]
I'm not using GitHub's "projects" feature so this is going to sit as an open issue. :D

## v0.1.0 roadmap
- [x] Upload to stat.ink!
- [x] Get monitoring mode working
- [x] Get standalone `-r` working
- [x] Implement `needs_sorted` map in `fetch_json()`
- [x] Fix bare command (don't get full results, numbers only then necessary GraphQL query/ies)
- [x] Sort scoreboard (set `rank_in_team` payload keys)
- [x] Improved stage shortname display
- [x] Handle unexplained 9403/9599 errors better (#22)
- [x] Support for S+ ranks
- [x] Send `medal` strings
- [x] Send `agent_variables`
- [x] Send `rank_in_team`
- [x] Send `rank_exp_change` (at end of series, or every open match)
- [x] Send `rank_up_battle` (at end of series, or every open match)
- [x] Send `challenge_win` and `challenge_lose` (5 wins/3 losses progress – only at end of series)
- [x] Retry on stat.ink Cloudflare issue (#23 & #24)
- [x] Fix `rank_before` & `rank_after` params
- [x] Sort battles (by timestamp) from exported JSONs on upload

**Comment by frozenpandaman** [comment]
## v0.1.1–v0.2.0 (ish) roadmap
- [ ] Splatfest battle support (not including Tricolor – no stat.ink support)
- [ ] Check for unuploaded results upon exiting monitoring mode (w/o requiring separate `-r` run)
- [ ] Support for S+ ranks
- [ ] Send scoreboard & gear screenshots
