### ISSUE TITLE
v0.2.0 roadmap

### ISSUE THREAD

**Issue by frozenpandaman** [frozenpandaman/s3s#49]
v0.1.0 roadmap:  #20

## v0.2.0 roadmap
- [x] Salmon Run support!!
- [x] Check for unuploaded results upon exiting monitoring mode (w/o requiring separate `-r` run) b002475, 4c02263
- [x] Implement `check_for_updates()` 17844cd
- [x] Implement `--blackout` flag 8bb0974
- [x] Implement `--getseed` flag (#74)
- [x] #41
- [x] #46 / #54
- [x] #52
- [x] #69 + #70
- [x] #35
- [x] #61

---

### v0.2.1+

- [ ] QOL: #50
- [ ] QOL: Send series progress for every battle (backwards compute or store state in memory, maybe w/ `-i` & `-r` only) #64
- [ ] QOL: Fully modular design (#17)
